# Generated by Django 2.2.4 on 2021-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(),
        ),
    ]
